### ISSUE TITLE
Method not found: 'UInt32 Microsoft.Xna.Framework.Color.get_PackedValue()

### ISSUE THREAD

**Issue by bartwe** [stefanhaan/Staxel-BetterSigns#3]
Hi, due to a change/optimization to the game the mod has been broken and requires a recompilation and reupload

mods.betterSigns.tiles.boardBrown
 System.MissingMethodException: Method not found: 'UInt32 Microsoft.Xna.Framework.Color.get_PackedValue()'.
   at BetterSigns.Staxel.TileState.BetterSignTileStateEntityLogic.Store()
   at Staxel.Logic.Entity.Store() in c:\hg\Staxel\Staxel\Logic\Entity.cs:line 86
   at BetterSigns.Staxel.TileState.BetterSignTileStateEntityBuilder.Spawn(EntityUniverseFacade facade, Tile tile, Vector3I location)
   at BetterSigns.Staxel.TileState.BetterSignTileStateBuilder.Instance(Vector3I location, Tile tile, Universe universe)
   at Staxel.Logic.Universe.FetchTileStateEntityLogic(Vector3I location, TileAccessFlags accessFlags, Tile& tile) in c:\hg\Staxel\Staxel\Logic\Universe.cs:line 733

**Comment by ghost** [comment]
Thanks for the poke! It's now uploaded with a rebuild against the latest libraries.
